---
- name: Disable swap
  command: swapoff -a

- name: Install ntpdate to synchronize time
  ansible.builtin.apt:
    name: ntpdate
    state: present
    update_cache: yes

- name: Synchronize system time
  ansible.builtin.command: ntpdate -s ntp.ubuntu.com
  changed_when: true

- name: Comment out swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^/swap.img'
    replace: '#/swap.img'

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure br_netfilter module is loaded
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Add br_netfilter to modules-load.d
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'

- name: Configure sysctl for Kubernetes networking
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'

- name: Apply sysctl parameters
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Configure containerd
  shell: containerd config default | sudo tee /etc/containerd/config.toml

- name: Enable SystemdCgroup in containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key and dearmor
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
