---
- name: Get the join command from the local file
  local_action: command cat ./join-command
  register: join_command_from_file
  changed_when: false
  become: false

- name: Join the worker nodes to the cluster
  shell: "sudo {{ join_command_from_file.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  become: true

